source "http://rubygems.org"

gem "rack"
gem "rake"
gem "sinatra"
gem "sinatra-reloader"
gem "sinatra-cross_origin", "~> 0.3.1"
gem "exifr"
gem "mimemagic"
gem "mini_magick", "~> 4.0.3"
gem "sidekiq", "~> 3.2.5"
gem "rest-client"
gem "addressable"
gem "minitest"
gem "erubis"
