addr: '0.0.0.0'

# run on port
port: 1234

# directory to store uploads
upload: 'upload'

# directory to store resized images
resize: 'resize'

# accept requests from
allow_origin: 'http://localhost:4567'